import { AlertCircle, CheckCircle2, Fan, Home, Settings2 } from "lucide-react";
import SeoHead from "@/components/site/SeoHead";
import { ActionButtons, FaqList, PageLayout, PageIntro, SectionHeading } from "@/components/site/SiteLayout";
import { IMAGE_URLS } from "@/lib/site";

const faqs = [
  { question: "What types of ACs do you repair?", answer: "We handle service requests for split ACs and window ACs. Share the brand, model and issue when you call so the requirement is clear." },
  { question: "Do you provide AC installation in Noida?", answer: "Yes, installation requests in Noida can be discussed for homes, offices and other properties. The site, AC type and installation requirement can be reviewed before work begins." },
  { question: "How often should an AC be serviced?", answer: "Many households schedule a service before the hotter months and whenever cooling, airflow, water leakage or unusual noise becomes a concern." },
  { question: "What should I do if my AC is not cooling?", answer: "Check that the power is on and the filters are not visibly blocked. If the issue continues, switch the unit off and contact a technician rather than continuing to run it." },
  { question: "Do you provide residential and commercial AC services?", answer: "Yes. We accept requirements for homes, societies, offices and commercial spaces across Noida." },
];

export default function ACServices() {
  return <PageLayout><SeoHead title="AC Repair, Servicing & Installation in Noida | Pratap Sons" description="Split and window AC repair, installation, servicing and maintenance in Noida for residential and commercial properties." path="/ac-services" type="Service" serviceType="Air conditioner repair, installation and servicing" /><PageIntro source="ac" eyebrow="AC repair & installation in Noida" title="Practical AC service for cooling problems, installation and maintenance" text="From an AC that is not cooling to a new split or window unit that needs installing, Pratap Sons provides straightforward AC service for Noida homes, societies, offices and commercial spaces." image={IMAGE_URLS.acInstallation} imageAlt="Air conditioner installation work on a building" />
    <section className="py-16" data-testid="ac-offerings-section"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="What we help with" title="One place for common AC service needs" text="Tell us the AC type, location and problem. We can then understand whether you need repair, installation or routine servicing." /><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[{ icon: Fan, title: "AC repair", text: "Cooling issues, water leakage, unusual noise and units that will not turn on." }, { icon: Settings2, title: "AC installation", text: "Support for installing split and window AC units at residential or commercial properties." }, { icon: CheckCircle2, title: "AC servicing", text: "Cleaning and maintenance requests to help keep the unit working as expected." }, { icon: Home, title: "Home & business", text: "Service requests for homes, offices, shops, societies and other local spaces." }].map(({ icon: Icon, title, text }, index) => <article className="border border-slate-200 bg-white p-6" key={title} data-testid={`ac-offering-${index + 1}`}><Icon className="size-7 text-teal-800" /><h3 className="mt-5 font-heading text-lg font-bold text-slate-950" data-testid={`ac-offering-title-${index + 1}`}>{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600" data-testid={`ac-offering-copy-${index + 1}`}>{text}</p></article>)}</div></div></section>
    <section className="border-y border-slate-200 bg-white py-16" data-testid="ac-problems-section"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 md:grid-cols-[0.8fr_1.2fr] lg:px-8"><SectionHeading eyebrow="Common problems" title="When your AC is not behaving normally" text="A small change in airflow or sound can be useful information. Mention the symptoms when you call so the service request starts with context." /><div className="grid gap-3 sm:grid-cols-2" data-testid="ac-problem-list">{["AC not cooling", "AC not turning on", "Water leakage", "Unusual noise or smell", "Weak airflow", "Gas or refrigerant-related concern", "Split AC installation", "Window AC service"].map((problem, index) => <div className="flex items-center gap-3 border border-slate-200 bg-[#fbfaf7] p-4 text-sm font-semibold text-slate-700" key={problem} data-testid={`ac-problem-${index + 1}`}><AlertCircle className="size-4 shrink-0 text-amber-600" />{problem}</div>)}</div></div></section>
    <section className="py-16" data-testid="ac-maintenance-section"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="grid gap-8 border border-teal-200 bg-teal-50 p-7 md:grid-cols-[1fr_auto] md:items-center md:p-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-800">Need AC service in Noida?</p><h2 className="mt-3 font-heading text-2xl font-extrabold text-slate-950" data-testid="ac-cta-title">Share the issue and your sector</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600" data-testid="ac-cta-copy">For residential or commercial AC service, a photo or short description on WhatsApp can help explain the requirement.</p></div><ActionButtons source="ac-page" /></div></div></section>
    <section className="border-t border-slate-200 bg-white py-16" data-testid="ac-faq-section"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Questions customers ask" title="AC service FAQs" text="Clear answers for common AC repair and installation questions in Noida." align="center" /><div className="mt-10"><FaqList items={faqs} source="ac" /></div></div></section>
  </PageLayout>;
}