import { AlertTriangle, Flame, Home, Power, ShieldCheck, Thermometer } from "lucide-react";
import SeoHead from "@/components/site/SeoHead";
import { ActionButtons, FaqList, PageLayout, PageIntro, SectionHeading } from "@/components/site/SiteLayout";
import { IMAGE_URLS } from "@/lib/site";

const faqs = [
  { question: "Can you repair a geyser that is not heating water?", answer: "Yes, you can contact us with the geyser type and symptoms. A technician can review the issue and explain the repair requirement." },
  { question: "Do you service electric geysers?", answer: "Electric geyser repair and servicing requests are welcome in Noida. Share the make, issue and location when you call or WhatsApp." },
  { question: "What should I do if the geyser is leaking?", answer: "Turn the appliance off and, if safe to do so, isolate its water and electrical supply. Avoid opening it yourself and contact a technician." },
  { question: "Do you repair room heaters?", answer: "Yes, room heater repair and servicing enquiries can be discussed for common power, heating and switching issues." },
];

export default function GeyserHeater() {
  return <PageLayout><SeoHead title="Geyser & Heater Repair in Noida | Pratap Sons" description="Geyser repair, water heater servicing and room heater repair in Noida for common heating, leakage and power issues." path="/geyser-heater-repair" type="Service" serviceType="Geyser and room heater repair" /><PageIntro source="heating" eyebrow="Geyser & heater repair in Noida" title="Help with water heating and room heater problems" text="Pratap Sons provides practical geyser servicing, water heater troubleshooting, electric geyser repair and room heater support for homes and local properties in Noida." image={IMAGE_URLS.geyserRepair} imageAlt="Technician working on a water heating appliance" />
    <section className="py-16" data-testid="heating-services-section"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Heating appliance service" title="Common geyser and heater work" text="Describe the problem clearly and stop using an appliance if it is leaking, sparking or behaving unsafely." /><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{[{ icon: Thermometer, title: "Geyser repair", text: "For water not getting hot, inconsistent heating and other geyser concerns." }, { icon: Power, title: "Electric geyser issues", text: "Support for power, switch, heating element and thermostat-related enquiries." }, { icon: Flame, title: "Room heater repair", text: "Repair and servicing enquiries for room heaters that do not switch on or heat properly." }, { icon: ShieldCheck, title: "Servicing", text: "Routine checks and maintenance requests for home heating appliances." }, { icon: Home, title: "Residential service", text: "Local service requests for houses, flats and residential societies in Noida." }, { icon: AlertTriangle, title: "Safety-first guidance", text: "If there is a leak, burning smell or sparking, switch off the appliance and seek help." }].map(({ icon: Icon, title, text }, index) => <article className="border border-slate-200 bg-white p-6" key={title} data-testid={`heating-service-${index + 1}`}><Icon className="size-7 text-teal-800" /><h3 className="mt-5 font-heading text-lg font-bold text-slate-950" data-testid={`heating-service-title-${index + 1}`}>{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600" data-testid={`heating-service-copy-${index + 1}`}>{text}</p></article>)}</div></div></section>
    <section className="border-y border-slate-200 bg-[#f1f5f3] py-16" data-testid="heating-problems-section"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 md:grid-cols-[1fr_0.9fr] lg:px-8"><div><SectionHeading eyebrow="Common problems" title="When heating is not working as it should" /><div className="mt-8 grid gap-3 sm:grid-cols-2" data-testid="heating-problem-list">{["Geyser not heating water", "Water not getting hot", "Leakage", "Heating element problem", "Heater not switching on", "Unusual smell or sound"].map((problem, index) => <div className="flex items-center gap-3 border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-700" key={problem} data-testid={`heating-problem-${index + 1}`}><span className="size-2 shrink-0 rounded-full bg-amber-500" />{problem}</div>)}</div></div><div className="border border-amber-200 bg-amber-50 p-7" data-testid="heating-safety-card"><AlertTriangle className="size-7 text-amber-700" /><h3 className="mt-5 font-heading text-xl font-bold text-slate-950" data-testid="heating-safety-title">A quick safety reminder</h3><p className="mt-3 text-sm leading-6 text-slate-700" data-testid="heating-safety-copy">For leakage, sparks, a burning smell or exposed wiring, turn the appliance off if it is safe to do so. Do not continue using it until it has been checked.</p></div></div></section>
    <section className="py-16" data-testid="heating-cta-section"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col gap-7 border border-teal-200 bg-teal-50 p-7 md:flex-row md:items-center md:justify-between md:p-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-teal-800">Need heating appliance help?</p><h2 className="mt-3 font-heading text-2xl font-extrabold text-slate-950" data-testid="heating-cta-title">Call or WhatsApp about your geyser or heater</h2><p className="mt-3 text-sm leading-6 text-slate-600" data-testid="heating-cta-copy">Mention the appliance type, issue and Noida location for a clearer service enquiry.</p></div><ActionButtons source="heating-page" /></div></div></section>
    <section className="border-t border-slate-200 bg-white py-16" data-testid="heating-faq-section"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Heating appliance questions" title="Geyser and heater FAQs" align="center" /><div className="mt-10"><FaqList items={faqs} source="heating" /></div></div></section>
  </PageLayout>;
}