import { Building2, Construction, Droplets, House, TriangleAlert } from "lucide-react";
import SeoHead from "@/components/site/SeoHead";
import { ActionButtons, FaqList, PageLayout, PageIntro, SectionHeading } from "@/components/site/SiteLayout";
import { IMAGE_URLS } from "@/lib/site";

const faqs = [
  { question: "Where do you provide water tanker service?", answer: "The service is focused on Noida. Share the sector, landmark and requirement when you call so the delivery location is clear." },
  { question: "Can I request water for a construction site?", answer: "Yes. Construction water supply is one of the requirements we can discuss. Mention the site location and expected need when you contact us." },
  { question: "Do you deliver water to homes and societies?", answer: "Residential homes, apartment societies and other local properties can enquire about water supply in Noida." },
  { question: "Can businesses request tanker water?", answer: "Yes. Commercial properties, offices and temporary requirements can contact us to discuss water delivery arrangements." },
];

export default function WaterTanker() {
  return <PageLayout><SeoHead title="Water Tanker Service in Noida | Residential & Commercial Supply" description="Water tanker and water delivery service in Noida for homes, societies, construction sites, commercial properties and urgent local requirements." path="/water-tanker-noida" type="Service" serviceType="Water tanker supply and delivery" /><PageIntro source="water" eyebrow="Water tanker service in Noida" title="Local water delivery for homes, sites and commercial requirements" text="Pratap Sons helps connect local customers in Noida with water tanker supply for residential properties, societies, construction sites, commercial spaces and temporary needs." image={IMAGE_URLS.waterTanker} imageAlt="Water tanker truck on a local road" />
    <section className="py-16" data-testid="water-use-cases-section"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Water supply requirements" title="Tell us where the water is needed" text="Different locations have different access and timing needs. Share the place, sector and use case so the enquiry is easy to understand." /><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{[{ icon: House, title: "Residential supply", text: "For homes, apartments and residential societies dealing with a temporary water requirement." }, { icon: Construction, title: "Construction sites", text: "Water delivery enquiries for building, civil work and other site requirements." }, { icon: Building2, title: "Commercial spaces", text: "Support for offices, shops, facilities and other commercial properties in Noida." }, { icon: TriangleAlert, title: "Urgent requirement", text: "If water is needed quickly, call with your location and the immediate situation." }].map(({ icon: Icon, title, text }, index) => <article className="border border-slate-200 bg-white p-6" key={title} data-testid={`water-use-case-${index + 1}`}><Icon className="size-7 text-teal-800" /><h3 className="mt-5 font-heading text-lg font-bold text-slate-950" data-testid={`water-use-case-title-${index + 1}`}>{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600" data-testid={`water-use-case-copy-${index + 1}`}>{text}</p></article>)}</div></div></section>
    <section className="border-y border-slate-200 bg-[#f1f5f3] py-16" data-testid="water-process-section"><div className="mx-auto grid max-w-7xl gap-12 px-4 sm:px-6 md:grid-cols-2 lg:px-8"><div><SectionHeading eyebrow="How to enquire" title="A clear request helps us plan the delivery" text="There are no fixed details shown here because each requirement depends on the location and use. Call or WhatsApp to discuss the practical next step." /><div className="mt-8 space-y-4" data-testid="water-process-list">{["Share your Noida sector or landmark", "Tell us whether it is residential, construction or commercial use", "Mention the urgency and any access details", "Confirm the delivery arrangement directly"] .map((step, index) => <div className="flex gap-4" key={step} data-testid={`water-process-step-${index + 1}`}><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-teal-800 text-sm font-bold text-white">{index + 1}</span><p className="pt-1 text-sm leading-6 text-slate-700">{step}</p></div>)}</div></div><div className="overflow-hidden border border-slate-200 bg-white"><img src={IMAGE_URLS.waterDelivery} alt="Water tanker delivering water near a property" width="1000" height="700" loading="lazy" className="aspect-[4/3] w-full object-cover" data-testid="water-delivery-image" /><div className="p-6"><div className="flex items-start gap-3"><Droplets className="mt-0.5 size-5 text-teal-800" /><div><h3 className="font-heading font-bold text-slate-950" data-testid="water-note-title">Water tanker service in Noida</h3><p className="mt-2 text-sm leading-6 text-slate-600" data-testid="water-note-copy">For the most useful response, include the delivery location and what the water is needed for.</p></div></div></div></div></div></section>
    <section className="py-16" data-testid="water-cta-section"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="border border-amber-200 bg-amber-50 p-7 md:flex md:items-center md:justify-between md:gap-8 md:p-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-800">Water tanker service in Noida</p><h2 className="mt-3 font-heading text-2xl font-extrabold text-slate-950" data-testid="water-cta-title">Call for water tanker service in Noida</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600" data-testid="water-cta-copy">Residential, construction and commercial enquiries are welcome. Share your location and requirement.</p></div><div className="mt-6 md:mt-0"><ActionButtons source="water-page" /></div></div></div></section>
    <section className="border-t border-slate-200 bg-white py-16" data-testid="water-faq-section"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><SectionHeading eyebrow="Water delivery questions" title="Water tanker FAQs" align="center" /><div className="mt-10"><FaqList items={faqs} source="water" /></div></div></section>
  </PageLayout>;
}